devices([
  "iPhone 15 Pro Max",
  "iPhone 15 Pro",
  "iPad Pro (12.9-inch) (6th generation)",
  "iPad Pro (11-inch) (4th generation)"
])

languages([
  "en-US"
])

scheme("TermitUITests")
output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
override_status_bar(true)
launch_arguments(["--snapshots"])
